### ISSUE TITLE
Improve inital database schema provision build.sql

### ISSUE THREAD

**Issue by madnight** [lafreak/Bango#12]
The build.sql https://github.com/lafreak/Bango/blob/master/build.sql should be reduced by using loops for account creation.

```SQL
DECLARE @i int = 0
WHILE @i < 5000
BEGIN
    SET @i = @i + 1
    INSERT INTO account (login, password, secondary)
	VALUES
	('bot+@i+', 'passwd', '00000000')
END
```

This comes in handy for later stress test account creations (1000 plus), which would be messy otherwise.

**Comment by lafreak** [comment]
You could add pull request with this change :P

**Comment by madnight** [comment]
I dont even know my snippet is valid SQL, its just what i think how it would look like ^^

**Comment by lafreak** [comment]
Done, now bot accounts number is as variable:
https://github.com/lafreak/Bango/blob/master/build.sql#L132
